### PR TITLE
Add aarch64 ffmpeg binary

### PR DESCRIPTION
**Pull request by odidev**
Added ffmpeg aarch64 binary from https://johnvansickle.com/ffmpeg/

### CODE REVIEW

**Comment by FirefoxMetzger** [comment]
This is a very nice contribution; thanks for that! I think we should add this library to the binaries.

That said, I am hesitant to merge this PR because we don't have good means of reviewing the binary. I'd feel much more comfortable if it came from one of the core members. I don't mean this in an offensive way; I just really want to avoid accidentally committing and serving a binary that might contain an unwanted payload (such as a virus or a backdoor) to a lot of people.

That said, if @almarklein is happy to merge this, we could go ahead. That said, it may be useful to discuss an good and secure procedure for adding binaries for missing architectures, since this is not an isolated issue (see also https://github.com/imageio/imageio/issues/628)

**Comment by almarklein** [comment]
Referencing https://github.com/imageio/imageio-ffmpeg/issues/52 where this contribution was discussed :)

**Comment by almarklein** [comment]
You are right that we should be careful with this. I had better contributed the file myself. I just downloaded the file and compared to what was contributed in this PR, and the MD5 hashes are equal.

Eventually it would indeed be much better to build all binaries ourselves. Or to make use of a source that does this, which is more transparent.

**Comment by FirefoxMetzger** [comment]
> I just downloaded the file and compared to what was contributed in this PR, and the MD5 hashes are equal.

You mean you compared the binary [this file](https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.2.2-arm64-static.tar.xz) and our binary? That's reassuring.

> Eventually it would indeed be much better to build all binaries ourselves. Or to make use of a source that does this, which is more transparent.

Agreed. I can make this the next feature I'll be working on after the new API is merged and documented.

**Comment by almarklein** [comment]
> You mean you compared the binary in this file and our binary? That's reassuring.

Yes, so it's about as good as having prepped this PR myself. Now we only have to assume.hope that this John van Sickle is not including evil code in the binaries that he publishes.

**Pull request merged**
